-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 26, 2022 at 11:01 PM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.1.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `kimo`
--

-- --------------------------------------------------------

--
-- Table structure for table `models_stickers`
--

CREATE TABLE `models_stickers` (
  `id` int(11) NOT NULL,
  `name` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `body` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `models_stickers`
--

INSERT INTO `models_stickers` (`id`, `name`, `body`) VALUES
(1, 'اسبور أبيض م28', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 6px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: center; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>اسبور أبيض</span>                                    </div>                                    <div>                                        <span>المقاس: </span>                                        <span>28</span>                                    </div>                                    <img src=\"\\img/png/002-undershirt-1.png\" style=\"display: block;\">                                </div>                            '),
(2, 'اسبور أبيض م30', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 6px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: center; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>اسبور أبيض</span>                                    </div>                                    <div>                                        <span>المقاس: </span>                                        <span>30</span>                                    </div>                                    <img src=\"\\img/png/002-undershirt-1.png\" style=\"display: block;\">                                </div>                            '),
(3, 'اسبور أبيض م34', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 6px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: center; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>اسبور أبيض</span>                                    </div>                                    <div>                                        <span>المقاس: </span>                                        <span>34</span>                                    </div>                                    <img src=\"\\img/png/002-undershirt-1.png\" style=\"display: block;\">                                </div>                            '),
(4, 'اسبور أبيض م36', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 6px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: center; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>اسبور أبيض</span>                                    </div>                                    <div>                                        <span>المقاس: </span>                                        <span>36</span>                                    </div>                                    <img src=\"\\img/png/002-undershirt-1.png\" style=\"display: block;\">                                </div>                            '),
(5, 'اسبور أبيض م40', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 6px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: center; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>اسبور أبيض</span>                                    </div>                                    <div>                                        <span>المقاس: </span>                                        <span>40</span>                                    </div>                                    <img src=\"\\img/png/002-undershirt-1.png\" style=\"display: block;\">                                </div>                            '),
(6, 'اسبور أبيض مM', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 6px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: center; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>اسبور أبيض</span>                                    </div>                                    <div>                                        <span>المقاس: </span>                                        <span>M</span>                                    </div>                                    <img src=\"\\img/png/002-undershirt-1.png\" style=\"display: block;\">                                </div>                            '),
(7, 'اسبور أبيض مL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 6px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: center; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>اسبور أبيض</span>                                    </div>                                    <div>                                        <span>المقاس: </span>                                        <span>L</span>                                    </div>                                    <img src=\"\\img/png/002-undershirt-1.png\" style=\"display: block;\">                                </div>                            '),
(8, 'شورت أبيض م28', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: شورت أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>28</span></div>                                    <img src=\"\\img/png/004-underwear-1.png\" style=\"display: block;\">                                </div>                            '),
(9, 'شورت أبيض م30', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: شورت أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>30</span></div>                                    <img src=\"\\img/png/004-underwear-1.png\" style=\"display: block;\">                                </div>                            '),
(10, 'شورت أبيض م34', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: شورت أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>34</span></div>                                    <img src=\"\\img/png/004-underwear-1.png\" style=\"display: block;\">                                </div>                            '),
(11, 'شورت أبيض م36', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: شورت أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>36</span></div>                                    <img src=\"\\img/png/004-underwear-1.png\" style=\"display: block;\">                                </div>                            '),
(12, 'شورت أبيض م40', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: شورت أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>40</span></div>                                    <img src=\"\\img/png/004-underwear-1.png\" style=\"display: block;\">                                </div>                            '),
(13, 'شورت أبيض مM', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: شورت أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>M</span></div>                                    <img src=\"\\img/png/004-underwear-1.png\" style=\"display: block;\">                                </div>                            '),
(14, 'شورت أبيض مL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: شورت أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>L</span></div>                                    <img src=\"\\img/png/004-underwear-1.png\" style=\"display: block;\">                                </div>                            '),
(15, 'سلب أبيض م28', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>سلب أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>28</span></div>                                    <img src=\"\\img/png/003-underwear.png\" style=\"display: block;\">                                </div>                            '),
(16, 'سلب أبيض م30', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>سلب أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>30</span></div>                                    <img src=\"\\img/png/003-underwear.png\" style=\"display: block;\">                                </div>                            '),
(17, 'سلب أبيض م34', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>سلب أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>34</span></div>                                    <img src=\"\\img/png/003-underwear.png\" style=\"display: block;\">                                </div>                            '),
(18, 'سلب أبيض م36', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>سلب أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>36</span></div>                                    <img src=\"\\img/png/003-underwear.png\" style=\"display: block;\">                                </div>                            '),
(19, 'سلب أبيض م40', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>سلب أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>40</span></div>                                    <img src=\"\\img/png/003-underwear.png\" style=\"display: block;\">                                </div>                            '),
(20, 'سلب أبيض مM', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>سلب أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>M</span></div>                                    <img src=\"\\img/png/003-underwear.png\" style=\"display: block;\">                                </div>                            '),
(21, 'سلب أبيض مL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>سلب أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>L</span></div>                                    <img src=\"\\img/png/003-underwear.png\" style=\"display: block;\">                                </div>                            '),
(22, 'نص كم م28', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: نص كم أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>28</span></div>                                    <img src=\"\\img/png/005-tshirt.png\" style=\"display: block;\">                                </div>                            '),
(23, 'نص كم م30', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: نص كم أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>30</span></div>                                    <img src=\"\\img/png/005-tshirt.png\" style=\"display: block;\">                                </div>                            '),
(24, 'نص كم م34', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: نص كم أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>34</span></div>                                    <img src=\"\\img/png/005-tshirt.png\" style=\"display: block;\">                                </div>                            '),
(25, 'نص كم م36', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: نص كم أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>36</span></div>                                    <img src=\"\\img/png/005-tshirt.png\" style=\"display: block;\">                                </div>                            '),
(26, 'نص كم م40', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: نص كم أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>40</span></div>                                    <img src=\"\\img/png/005-tshirt.png\" style=\"display: block;\">                                </div>                            '),
(27, 'نص كم مM', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: نص كم أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>M</span></div>                                    <img src=\"\\img/png/005-tshirt.png\" style=\"display: block;\">                                </div>                            '),
(28, 'نص كم مL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: نص كم أبيض</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>L</span></div>                                    <img src=\"\\img/png/005-tshirt.png\" style=\"display: block;\">                                </div>                            '),
(29, 'هاف كول م2', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>2</span>                                    </div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(30, 'هاف كول م4', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: هاف كول</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>4</span></div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(33, 'هاف كول م6', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>6</span>                                    </div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(34, 'هاف كول م8', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول</span></div>                                    <div>                                        <span>المقاس: </span>                                        <span>8</span>                                    </div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(35, 'هاف كول م10', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول&nbsp;</span></div>                                    <div>                                        <span>المقاس: 10</span></div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(36, 'هاف كول م12', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول</span>                                    </div>                                    <div>                                        <span>المقاس: 12</span><span></span></div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(37, 'هاف كول م14', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول</span>                                    </div>                                    <div>                                        <span>المقاس: 14</span><span></span></div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(41, 'هاف كول مS', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول</span>                                    </div>                                    <div>                                        <span>المقاس: S</span><span></span></div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(42, 'هاف كول مM', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول</span>                                    </div>                                    <div>                                        <span>المقاس: M</span><span></span></div><div><span><br></span></div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(43, 'هاف كول مL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول</span>                                    </div>                                    <div>                                        <span>المقاس: L</span><span></span></div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(44, 'هاف كول مXL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول</span>                                    </div>                                    <div>                                        <span>المقاس: XL</span><span></span></div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(45, 'هاف كول م2XL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول</span>                                    </div>                                    <div>                                        <span>المقاس: 2XL</span></div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(46, 'هاف كول م3XL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول</span>                                    </div>                                    <div>                                        <span>المقاس: 3XL</span><span></span></div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(47, 'هاف كول م4XL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>هاف كول</span>                                    </div>                                    <div>                                        <span>المقاس: 4XL</span><span></span></div>                                    <img src=\"\\img/png/006-sweater.png\" style=\"display: block;\">                                </div>                            '),
(52, 'طقم شورت م28', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم شورت</span>                                    </div>                                    <div>                                        <span>المقاس: 28</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(53, 'طقم شورت م30', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم شورت</span>                                    </div>                                    <div>                                        <span>المقاس: 30</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(54, 'طقم شورت م34', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم شورت</span>                                    </div>                                    <div>                                        <span>المقاس: 34</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(55, 'طقم شورت م36', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم شورت</span>                                    </div>                                    <div>                                        <span>المقاس: 36</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(56, 'طقم شورت م40', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم شورت</span>                                    </div>                                    <div>                                        <span>المقاس: 40</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(57, 'طقم شورت مM', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم شورت</span>                                    </div>                                    <div>                                        <span>المقاس: M</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(58, 'طقم شورت مL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم شورت</span>                                    </div>                                    <div>                                        <span>المقاس: L</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(59, 'طقم سلب م28', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم سلب</span>                                    </div>                                    <div>                                        <span>المقاس: 28</span><span></span></div>                                    <img src=\"\\img/png/008-zyad-1.png\" style=\"display: block;\">                                </div>                            '),
(60, 'طقم سلب م30', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم سلب</span>                                    </div>                                    <div>                                        <span>المقاس: 30</span><span></span></div>                                    <img src=\"\\img/png/008-zyad-1.png\" style=\"display: block;\">                                </div>                            '),
(62, 'طقم سلب م34', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم سلب</span>                                    </div>                                    <div>                                        <span>المقاس: 34</span><span></span></div><div><span><br></span></div>                                    <img src=\"\\img/png/008-zyad-1.png\" style=\"display: block;\">                                </div>                            '),
(63, 'طقم سلب م36', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم سلب</span>                                    </div>                                    <div>                                        <span>المقاس: 36</span><span></span></div>                                    <img src=\"\\img/png/008-zyad-1.png\" style=\"display: block;\">                                </div>                            '),
(64, 'طقم سلب م40', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم سلب</span>                                    </div>                                    <div>                                        <span>المقاس: 40</span><span></span></div>                                    <img src=\"\\img/png/008-zyad-1.png\" style=\"display: block;\">                                </div>                            '),
(65, 'طقم سلب مM', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم سلب</span>                                    </div>                                    <div>                                        <span>المقاس: M</span><span></span></div>                                    <img src=\"\\img/png/008-zyad-1.png\" style=\"display: block;\">                                </div>                            '),
(66, 'طقم سلب مL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم سلب</span>                                    </div>                                    <div>                                        <span>المقاس: L</span><span></span></div>                                    <img src=\"\\img/png/008-zyad-1.png\" style=\"display: block;\">                                </div>                            '),
(67, 'طقم حمالة بناتي م28', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم حمالة بناتي</span>                                    </div>                                    <div>                                        <span>المقاس: 28</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(68, 'طقم حمالة بناتي م30', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم حمالة بناتي</span>                                    </div>                                    <div>                                        <span>المقاس: 30</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(69, 'طقم حمالة بناتي م34', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم حمالة بناتي</span>                                    </div>                                    <div>                                        <span>المقاس: 34</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(70, 'طقم حمالة بناتي م36', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم حمالة بناتي</span>                                    </div>                                    <div>                                        <span>المقاس: 36</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(71, 'طقم حمالة بناتي م40', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم حمالة بناتي</span>                                    </div>                                    <div>                                        <span>المقاس: 40</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(72, 'طقم حمالة بناتي مM', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم حمالة بناتي</span>                                    </div>                                    <div>                                        <span>المقاس: M</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(73, 'طقم حمالة بناتي مL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم حمالة بناتي</span>                                    </div>                                    <div>                                        <span>المقاس: L</span><span></span></div>                                    <img src=\"\\img/png/007-zyad.png\" style=\"display: block;\">                                </div>                            '),
(74, 'طقم توب م28', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب</span>                                    </div>                                    <div>                                        <span>المقاس: 28</span><span></span></div>                                    <img src=\"\\img/png/010-salma.png\" style=\"display: block;\">                                </div>                            '),
(75, 'طقم توب م30', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب</span>                                    </div>                                    <div>                                        <span>المقاس: 30</span><span></span></div>                                    <img src=\"\\img/png/010-salma.png\" style=\"display: block;\">                                </div>                            ');
INSERT INTO `models_stickers` (`id`, `name`, `body`) VALUES
(76, 'طقم توب م34', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب</span>                                    </div>                                    <div>                                        <span>المقاس: 34</span><span></span></div>                                    <img src=\"\\img/png/010-salma.png\" style=\"display: block;\">                                </div>                            '),
(77, 'طقم توب م36', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب</span>                                    </div>                                    <div>                                        <span>المقاس: 36</span><span></span></div>                                    <img src=\"\\img/png/010-salma.png\" style=\"display: block;\">                                </div>                            '),
(78, 'طقم توب م40', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب</span>                                    </div>                                    <div>                                        <span>المقاس: 40</span><span></span></div>                                    <img src=\"\\img/png/010-salma.png\" style=\"display: block;\">                                </div>                            '),
(79, 'طقم توب مM', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب</span>                                    </div>                                    <div>                                        <span>المقاس: M</span><span></span></div>                                    <img src=\"\\img/png/010-salma.png\" style=\"display: block;\">                                </div>                            '),
(80, 'طقم توب مL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب</span>                                    </div>                                    <div>                                        <span>المقاس: L</span><span></span></div>                                    <img src=\"\\img/png/010-salma.png\" style=\"display: block;\">                                </div>                            '),
(81, 'طقم توب سلب م28', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب سلب</span>                                    </div>                                    <div>                                        <span>المقاس: 28</span><span></span></div>                                    <img src=\"\\img/png/009-salma-1.png\" style=\"display: block;\">                                </div>                            '),
(82, 'طقم توب سلب م30', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب سلب</span>                                    </div>                                    <div>                                        <span>المقاس: 30</span><span></span></div>                                    <img src=\"\\img/png/009-salma-1.png\" style=\"display: block;\">                                </div>                            '),
(83, 'طقم توب سلب م34', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب سلب</span>                                    </div>                                    <div>                                        <span>المقاس: 34</span></div>                                    <img src=\"\\img/png/009-salma-1.png\" style=\"display: block;\">                                </div>                            '),
(84, 'طقم توب سلب م36', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب سلب</span>                                    </div>                                    <div>                                        <span>المقاس: 36</span><span></span></div>                                    <img src=\"\\img/png/009-salma-1.png\" style=\"display: block;\">                                </div>                            '),
(85, 'طقم توب سلب م40', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب سلب</span>                                    </div>                                    <div>                                        <span>المقاس: 40</span><span></span></div>                                    <img src=\"\\img/png/009-salma-1.png\" style=\"display: block;\">                                </div>                            '),
(86, 'طقم توب سلب مM', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب سلب</span>                                    </div>                                    <div>                                        <span>المقاس: M</span><span></span></div>                                    <img src=\"\\img/png/009-salma-1.png\" style=\"display: block;\">                                </div>                            '),
(87, 'طقم توب سلب مL', '                                <div class=\"card mx-auto position-relative\" id=\"card_preview\"  style=\"padding: 7px; font-size: 12px; font-family: cairo; border-style: none; align-items: normal; justify-content: normal; line-height: 2;\">                                    <div>                                        <span>الصنف: </span>                                        <span>طقم توب سلب</span>                                    </div>                                    <div>                                        <span>المقاس: L</span><span></span></div>                                    <img src=\"\\img/png/009-salma-1.png\" style=\"display: block;\">                                </div>                            ');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `models_stickers`
--
ALTER TABLE `models_stickers`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `models_stickers`
--
ALTER TABLE `models_stickers`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=88;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
